INDICES = {
    'S&P 500': '%5EGSPC',
    'Dow Jones Industrial Average': '%5EDJI',
    'NASDAQ Composite': '%5EIXIC',
    'NYSE COMPOSITE (DJ)': '%5ENYA',
    'NYSE AMEX COMPOSITE INDEX': '%5EXAX',
    'Russell 2000': '%5ERUT',
    'Vix': '%5EVIX',
    'FTSE 100': '%5EFTSE',
    'DAX': '%5EGDAXI',
    'CAC 40': '%5EFCHI',
    'ESTX50 EUR P': '%5ESTOXX50E',
    'EURONEXT 100': '%5EN100',
    'BEL 20': '%5EBFX',
    'MICEX Index': 'MICEXINDEXCF.ME',
    'Nikkei 225': '%5EN225',
    'HANG SENG INDEX': '%5EHSI',
    'SSE Composite Index': '000001.SS',
    'STI Index': '%5ESTI',
    'S&P/ASX 200': '%5EAXJO',
    'ALL ORDINARIES': '%5EAORD',
    'S&P BSE SENSEX': '%5EBSESN',
    'Jakarta Composite Index': '%5EJKSE',
    'FTSE Bursa Malaysia KLCI': '%5EKLSE',
    'S&P/NZX 50 INDEX GROSS': '%5ENZ50',
    'KOSPI Composite Index': '%5EKS11',
    'TSEC weighted index': '%5ETWII',
    'S&P/TSX Composite index': '%5EGSPTSE',
    'IBOVESPA': '%5EBVSP',
    'IPC MEXICO': '%5EMXX',
    'IPSA SANTIAGO DE CHILE': '%5EIPSA',
    'MERVAL BUENOS AIRES': '%5EMERV',
    'TA-125': '%5ETA100',
    'EGX 30 INDEX': '%5ECASE30'
}